### ISSUE TITLE
装上调不出来啊，也没按钮，也没插件选项

### ISSUE THREAD

**Issue by abcmiao** [xeden3/joplin-plugin-kity-minder#1]
说的不明不白，json文件咋用？
装上了，不管本地装还是搜索装，都没出现那个brain图标

**Comment by xeden3** [comment]
按照标准安装理论上是会有brain图标出现的，这个是joplin标准代码部分，如果没有图标出来，考虑以下可能性
1 本机的joplin插件安装环境是否存在被防火墙锁住的可能性，查看系统日志，或者另外一台机器尝试。
2 安装版本不对，可以尝试使用最新joplin版本进行安装，并对比安装其他插件功能是否也存在同样问题。

**Comment by xeden3** [comment]
请参考这个Issues
https://github.com/xeden3/joplin-plugin-kity-minder/issues/4
