### ISSUE TITLE
There is not any icon for open Kity minder editor

### ISSUE THREAD

**Issue by Eduardo3382** [xeden3/joplin-plugin-kity-minder#10]
Thanks for developing this plugin!
I have seen there is not any icon to open a mindMap editor nor a menu option to open it.
At least I have not seen them in linux, Ubuntu 22.04
Joplin 2.9.17 (prod, linux)
Kity Minder v1.0.9

see https://discourse.joplinapp.org/t/mind-map/4859/33?u=eduardo

![Screenshot from 2022-12-06 16-43-57](https://user-images.githubusercontent.com/39868347/206176366-fd2dc1d4-d791-4997-aadd-9aeb23cdf7e7.png)
![Screenshot from 2022-12-07 09-03-36](https://user-images.githubusercontent.com/39868347/206176380-1b20ce36-70e1-4567-b37b-75b31d02418f.png)

**Comment by xeden3** [comment]
Please use version 2.8.8. 2.9.X is a pre-release version. Many people have reported that there is no icon. Wait for the official release to see if you need to update the API

**Comment by xeden3** [comment]
Please use version 2.8.8. 2.9.4 is a pre-release version. Many people have reported that there is no icon. Wait for the official release to see if you need to update the API
