### ISSUE TITLE
Plugin Doesn't work on MacOS Joplin

### ISSUE THREAD

**Issue by duxswhatdux** [xeden3/joplin-plugin-kity-minder#13]
After installing the plugin in Joplin using Mac Catalina, the plugin does not display language option in the Options menu, and the Action icon or menu is not present. 
![Kity Action Icon](https://user-images.githubusercontent.com/45373146/208326984-716d7b3c-68a4-40d1-87e3-3271747128bd.png)
![Kity Options Plugins](https://user-images.githubusercontent.com/45373146/208326991-c9da046a-a21b-4449-8fae-f8d0efd5b0ae.png)

**Comment by 553531284** [comment]
#10 
原来有人反馈过这个问题，但是现在2.9.17仍然有问题。

**Comment by xeden3** [comment]
Joplin修改了API，这个问题在1.0.11版上修复了

**Comment by xeden3** [comment]
> #10 原来有人反馈过这个问题，但是现在2.9.17仍然有问题。
Joplin修改了API，这个问题在1.0.11版上修复了
