### ISSUE TITLE
Unable to use it on Linux Joplin

### ISSUE THREAD

**Issue by AleMunin** [xeden3/joplin-plugin-kity-minder#15]
Hi, loved the idea of the project.

I am not sure if this is an issue, but I downloaded the plugin from inside joplin, however the toggle buttons like in the image never appears on screen.

Is that a dependency issue?

**Comment by ncatanchin** [comment]
@AleMunin - had the same confusion myself a few weeks ago. None of the methods to activate mindmap mode were working or visible.

Taking a look at the Developer Tools Console - plugins are initialised during the Joplin loading / boot-up process. We can see below that the mindmap plugin is crashing out:

![image](https://user-images.githubusercontent.com/2169122/214087714-ef8a81fb-23f7-45f1-ae0c-a4f8716dee87.png)

and specifically:

`Error: ENOENT: no such file or directory, stat '/tmp/joplin-mindmap-plugin/'`

Confirmed the directory was missing, which it was, so I created it:

```
$ mkdir /tmp/joplin-mindmap-plugin
```

Restarted Joplin, and the mindmap icon is now visible

![image](https://user-images.githubusercontent.com/2169122/214091533-078c129c-12bf-45a4-929d-3de56c37059a.png)

Seems to be working well for me from there.

Please do note @xeden3's comment here: https://github.com/xeden3/joplin-plugin-kity-minder/issues/10#issuecomment-1352542433 -

**Comment by xeden3** [comment]
Is the clearDiskCache function problem as DrawIO plugin.
pls use v 1.0.10
I create a new function to fix it
