### ISSUE TITLE
doesn't work in Joplin 2.9.17

### ISSUE THREAD

**Issue by boycezhao** [xeden3/joplin-plugin-kity-minder#16]
Joplin 2.9.17
plugin version v1.0.9

In Joplin, no function button appears

**Comment by socarpl** [comment]
It seems, on both systems, is the same case as mentioned in issue #15 
**Workaround** is to create manually directories:

- on Linux: `/tmp/joplin-mindmap-plugin`
- on Windows: `%temp%\joplin-mindmap-plugin`

After creating those and fully restarting the app icon and edit abilities are back again

**Comment by bluesheepcj** [comment]
Try this: 
https://github.com/marc0l92/joplin-plugin-drawio/issues/17#issuecomment-1418258026
Exactly the same problem,  it can be fixed on my Macbook.
But this is a temporary solution, after all, the temporary folder will be replaced at any time.

**Comment by xeden3** [comment]
Is the clearDiskCache function problem as DrawIO plugin.
pls use v 1.0.10
