### ISSUE TITLE
已存在的脑图无法重新打开

### ISSUE THREAD

**Issue by hhaishen** [xeden3/joplin-plugin-kity-minder#17]
Joplin 2.9.17 (prod, win32)

客户端 ID: 4abe1d56f89047e8bfb2318e0479d0b0
同步版本：3
配置文件版本：41
支持的密钥链：是

修订：a84a8e7

我在整理完脑图之后进行保存，但我想重新打开进行编辑时便无法重新打开，点击 Edit 时会给我打开一个新的脑图，这个问题只出现在我第一个绘画脑图，后面我想复现问题，进行与之前相同的操作，但是无法再复现出同样的结果。导致我现在也不太敢继续在 Joplin 中完善我的脑图，我怕再次出现同样的情况。 如果方便的话能帮忙看下这个问题吗，万分感激！
@xeden3 

如果有需要，我可以将 joplin 中对应的笔记以 jex 格式进行导出并提供！

![rysfr-8vcsm](https://user-images.githubusercontent.com/122429037/228424587-84363be9-ec76-4d38-b827-aa1abff97cd0.gif)

**Comment by hhaishen** [comment]
> 这个问题我们一直没发现过，你可以试试更新1.0.12版本再测下，或者换一台系统也测下，如果还在，可以将jex文件发给我看

当前所使用的插件版本是：1.0.12，我在办公与家庭电脑上都尝试了对应操作还是一样的。 您这边方便留个邮箱吗，我将 jex 文件发给您

**Comment by xeden3** [comment]
james@sctmes.com 可以发这个邮箱

**Comment by hhaishen** [comment]
> [james@sctmes.com](mailto:james@sctmes.com) 可以发这个邮箱，请同时提供操作截图，方便能重现问题。 我在本机稍微测试了下，没有出现这个问题。
> 
> ![动画1](https://user-images.githubusercontent.com/38025067/230639228-68926f7f-b543-4c6b-856f-30d2f438fec2.gif) [ ![动画1](https://user-images.githubusercontent.com/38025067/230639228-68926f7f-b543-4c6b-856f-30d2f438fec2.gif) ](https://user-images.githubusercontent.com/38025067/230639228-68926f7f-b543-4c6b-856f-30d2f438fec2.gif) [ ](https://user-images.githubusercontent.com/38025067/230639228-68926f7f-b543-4c6b-856f-30d2f438fec2.gif)

jex 文件已发到指定邮箱~

**Comment by hhaishen** [comment]
> [james@sctmes.com](mailto:james@sctmes.com) 可以发这个邮箱，请同时提供操作截图，方便能重现问题。 我在本机稍微测试了下，没有出现这个问题。

jex 文件已发到指定邮箱~

**Comment by xeden3** [comment]
问题得到解决，由于单引号'对json格式进行了破坏，在1.0.15.版本进行了修复
