### ISSUE TITLE
Constant pop-ups, previously maintained maps cannot be used.

### ISSUE THREAD

**Issue by bluesheepcj** [xeden3/joplin-plugin-kity-minder#19]
My mind map keeps showing this error and immediately pops up again after clicking OK, making it impossible to perform any operations. Now I cannot modify or view the map. Is there any way to fix this problem? Thank you.

System:
<img width="280" alt="image" src="https://github.com/xeden3/joplin-plugin-kity-minder/assets/5466892/85dfd397-e3b2-4cc9-986b-bd2d2bed3961">

APP info:
Joplin for Desktop

Copyright © 2016-2023 Laurent Cozic
Joplin 2.10.19 (prod, darwin)

客户端 ID: 16814749eda84cf0a046b5454c6ca971
同步版本：3
配置文件版本：42
支持的密钥链：是

修订：1100ab0

Csv Import: 1.0.1
Draw.io: 2.2.0
Kity Minder: 1.0.16
PlantUML2: 1.11.0

<img width="1110" alt="image" src="https://github.com/xeden3/joplin-plugin-kity-minder/assets/5466892/115edf51-d2a8-4485-bca5-9103929ccbaa">

脑图的节点中包含跨域图片，导出的 png 中节点图片不显示，你可以替换掉这些跨域的图片并重试。
The nodes in the mind map contain cross-domain images. The node images may not be displayed in the exported PNG file. You can replace these cross-domain images and try again.

**Comment by xeden3** [comment]
你可以导出当前文档的jex文件发到github上么，我可以导入查看下。
