### ISSUE TITLE
English language support

### ISSUE THREAD

**Issue by martin-freitag** [xeden3/joplin-plugin-kity-minder#2]
Many thanks for this great plugin! I downloaded an manually installed this plugin and as far as I tested it, it perfectly fits my needs to integrate mindmaps into Joplin. 
Is there any way to provide english language support for the GUI? Not that this is super urgent, but would be great to have in the long run.

**Comment by noiseexplosion** [comment]
seconding this, this is the best implementation of diagrams available. i'd be happy to look over the translations too

**Comment by icewind** [comment]
Would also love to see english support

**Comment by arszagi** [comment]
very good plugin, great job, but with English support this plugin will be just perfect!

**Comment by xeden3** [comment]
Version 1.0.7 starts to support multiple languages ​​and uses English as the default language. You can reinstall version 1.0.7 and select the language in the plugin configuration
