### ISSUE TITLE
kity-mind version is mislead

### ISSUE THREAD

**Issue by WanderHuang** [xeden3/joplin-plugin-kity-minder#22]
<img width="1315" alt="Screenshot 2023-11-14 at 20 31 29" src="https://github.com/xeden3/joplin-plugin-kity-minder/assets/18475942/a34b30a5-36dd-4cd0-a118-71bf25e190dc">

**Q: Can this `local-kity-minder` version be managed by git? If this is not clear, many people can't use this PLUGIN in his working project.**

**Comment by xeden3** [comment]
The local-kity-minder can be maintained at the following address: 

https://github.com/xeden3/joplin-plugin-kity-minder/tree/main/src/local-kity-minder. 

Currently, this portion of the source code hasn't undergone many changes and is developed based on the https://github.com/wythe0102/local-kity-minder project.
