### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by sim0nwan9** [xeden3/joplin-plugin-kity-minder#4]
install 1.0.4 but i can not find this Plug-ins
![image](https://user-images.githubusercontent.com/55452739/193206014-51ac62e7-065b-4492-8ba6-a9bbca32722e.png)

**Comment by xeden3** [comment]
![image](https://user-images.githubusercontent.com/38025067/201012159-93a8f01b-0d05-478a-a05d-ef8948d9cc09.png)

**Comment by xeden3** [comment]
Version 1.0.7 of the plugin has added drop-down menu options
You can add new mind map  by toolbar buttons or drop-down menu options.

**Comment by xeden3** [comment]
Please use Joplin version 2.8.8, 2.9.4 is a pre-release version, there have been feedback from many people that there is no icon
Or reinstall ver 1.0.7 , you can add new mindmap by drop-down menu.

![image](https://user-images.githubusercontent.com/38025067/201176760-a7527262-3a9d-4f7d-8e38-840ad1327309.png)
