### ISSUE TITLE
window下安装成功无打开图标

### ISSUE THREAD

**Issue by peterlinux2010** [xeden3/joplin-plugin-kity-minder#6]
系统环境：window10
Joplin版本：2.9.4
现象：成功安装插件，在插件管理器中也可以正常显示，但主界面右上角无对应打开思维导图的图标

**Comment by xeden3** [comment]
请使用2.8.8版本，2.9.4是预发布版本，已经有多人反馈没有图标，等正式发布了再看是否需要更新API

**Comment by xeden3** [comment]
Version 1.0.7 of the plugin has added drop-down menu options
You can add new mind map  by toolbar buttons or drop-down menu options.

**Comment by xzhlksh** [comment]
@xeden3 2.9.17已经是release版本，新增的代理同步功能在国内算是半个刚需，能否针对该release版本更新api呢？
