### ISSUE TITLE
Export the mindmap data to markdown etc.

### ISSUE THREAD

**Issue by janklostermann** [xeden3/joplin-plugin-kity-minder#8]
Thanks for that cool plugin!
I have seen the core component [kityminder-editor](https://github.com/fex-team/kityminder-editor) does have the capability to export to json, txt, md, svg, png (I guessed right seeing those in the chinese text?)

Would it be possible to make this export available in the plug-in, e.g. via the existing right-click context menu on the image shown in the previewer? 
Having an additional entry `Export >` below the `Copy image`. Or without submenu just adding the 5 options flat.
Or providing it within the editor.

That would be great for some of us! 
See https://discourse.joplinapp.org/t/mind-map/4859

**Comment by xeden3** [comment]
Based on kityminder is using png format file to displayed on joplin, so you can directly save the png format through a right-click menu

![image](https://user-images.githubusercontent.com/38025067/207772594-27184422-9893-41bc-8054-dec3277bea00.png)

But I will consider adding a key to save other formats such as text, json, md

**Comment by janklostermann** [comment]
Thanks for considering! I guess md would be the most interesting. :-)
By the way, just out of curiosity: Where do you store the structured data of the mindmap? Within the png as well?

**Comment by janklostermann** [comment]
I discovered that by right-clicking on a node in the kityminder-editor there is also import and export node available. 
![grafik](https://user-images.githubusercontent.com/11610051/208072875-757793ba-caaf-4450-b268-ef69ebf409ed.png)

But apparently they only consider txt format. Providing a selector/configuration to choose markdown (and/or even JSON) would be great.
