### ISSUE TITLE
As mindmap viewer/editor for existing markdown notes

### ISSUE THREAD

**Issue by janklostermann** [xeden3/joplin-plugin-kity-minder#9]
Thanks again for your great plugin!
I have just discovered, that the [kityminder-editor](https://github.com/fex-team/kityminder-editor), that you use as foundation of your plugin is also capable of importing markdown. 

Would it be possible to use this capability provide an alternative previewer in this own pane that shows the note not as the usual interpreted markdown text, but as mindmap?
The user could then choose to view the markdown as text or as mindmap

The ultimate idea would be the ability to even edit the markdown through the mindmap-editor then. 
But this creates the same troubles as for all WYSIWYG-editors in terms of not corrupting the original - including the [RichText editor that Joplin already provides](https://joplinapp.org/rich_text_editor/): The particular markdown formating might have meaning to the user, even if it does not have meaning to the interpreter (previewer, editor, ...), in this case `kityminder-editor`. If the editor then does alter the markdown and does not respect these "external" especialities (that it does not (and can not) know of) when saving, then this data/information is lost to the user (even if the interpreter does not even perceive this). 
Examples of data at risk might be: existing frontmatter yaml, whitespaces and new-lines, choice of bullet point symbol, syntax extentions from other plugins, etc.
Therefore such an editing should either be 100% not-corrupting or be switched-off by default. Enabling should only be possible after actively conforming that the user is aware of the potential corruptions. 

Thanks for considering.

**Comment by xeden3** [comment]
Thanks for your advice
Because I only use markdown on joplin, I am not familiar with the interface of rich text
I'll look into the possibilities for this part.

**Comment by janklostermann** [comment]
Does this "closed as completed" mean that the preview of an existing markdown note as a (kityminder-) mindmap is already available?

Maybe to clarify my idea: a markdown note such as:
```
# topic
This topic is about testing
* part 1
* part 2

## test

## test2
details on test2
### sub-test2
more diving into it
```
would result in
![2c4b297f2dd64014b350d1bfb160a658](https://user-images.githubusercontent.com/11610051/208064687-910a92bd-13e7-4bd3-b0d0-059306b6d6fb.png)


I discovered that by right-clicking on a node in the kityminder-editor there is also import and export available. But these do not work as expected, as they do not care about the markdown structure. It seems that the data is interpreted as in txt format.
